export { default as logo } from "./loo.png"
export { default as photo1 } from "./microsoft.jpg"
export { default as photo2 } from "./wolfgang.jpg"
export { default as photo3 } from "./nathan.jpg"
export { default as photo4 } from "./brooke.jpg"
export {default as photo5} from "./julius.jpg"